version: '3.7'
services:
  db:
    image: mariadb
    container_name: "database-vend"
    env_file:
      - ./mariadb.env
    ports:
     - 3306
    volumes:
      - vend-data:/var/lib/mysql
  vendproxy:
    build:
      context: ./
      dockerfile: Dockerfile
      target: vendproxy
      labels:
        au.com.oxipay.vend.description: "Vend Application Proxy for Oxipay"
        au.com.oxipay.vend.publisher: "FlexiGroup"
    env_file: 
      - ./vendproxy.env
    image: 844996184919.dkr.ecr.ap-southeast-2.amazonaws.com/oxipay-vend:latest
    container_name: "proxy-vend"
    depends_on:
      - db
    ports:
      - 5000:5000
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
      target: nginx
    image: 844996184919.dkr.ecr.ap-southeast-2.amazonaws.com/nginx-vend:latest
    container_name: "nginx-vend"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - vendproxy
volumes:
    vend-data:
