version: '3.7'
services:
  db:
    image: mariadb
    env_file:
      - ./mariadb.env
    ports: 
     - 3306
    healthcheck:
      test: ["CMD","mysqladmin", "ping", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1s
    volumes: 
      - vend-data:/var/lib/mysql
  vendproxy:
    build: 
      context: ./
      dockerfile: Dockerfile
      labels:
        au.com.oxipay.vend.description: "Vend Application Proxy for Oxipay"
        au.com.oxipay.vend.publisher: "FlexiGroup"
    image: 844996184919.dkr.ecr.ap-southeast-2.amazonaws.com/oxipay-vend:latest
    env_file:
      - ./vendproxy.env    
    ports: 
     - 5000
    

    depends_on:
      - db
volumes:
    vend-data: 
